### ISSUE TITLE
Configuration error

### ISSUE THREAD

**Issue by SlimeDog** [FlailoftheLord/FishyLecterns#7]
Just a heads-up.

Spigot 1.18.1-3369 introduced new configuration management.

FishyLecterns 1.2
On server start-up (ie, on plugin enable)
```
[15:18:30] [Server thread/INFO]: [FishyLecterns] Enabling FishyLecterns v1.2
[15:18:30] [Server thread/INFO]: [FishyLecterns] registered Lectern Listener...^[[m
[15:18:30] [Server thread/ERROR]: Error occurred while enabling FishyLecterns v1.2 (Is it up to date?)
java.lang.ClassCastException: class org.bukkit.configuration.MemorySection cannot be cast to class java.util.Set (org.bukkit.configuration.MemorySection is in unnamed module of loader java.net.URLClassLoader @3d646c37; java.util.Set is in module java.base of loader 'bootstrap')
        at me.flail.fishylecterns.LecternLocations.<init>(LecternLocations.java:42) ~[?:?]
        at me.flail.fishylecterns.FishyLecterns.loadLecternsFromFile(FishyLecterns.java:78) ~[?:?]
        at me.flail.fishylecterns.FishyLecterns.onEnable(FishyLecterns.java:42) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:526) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3369-Spigot-8965a50-2a2caa7]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:440) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3369-Spigot-8965a50-2a2caa7]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3369-Spigot-8965a50-2a2caa7]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3369-Spigot-8965a50-2a2caa7]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:262) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3369-Spigot-8965a50-2a2caa7]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:994) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3369-Spigot-8965a50-2a2caa7]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3369-Spigot-8965a50-2a2caa7]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```
This error did not occur previously.

**Comment by SlimeDog** [comment]
The same content does not fail on Paper 1.18.1-84, which presumably has the same methods from upstream.

**Comment by FlailoftheLord** [comment]
seems like a broken java refference error, if the plugin works on paper but doesn't on spigot, it's most likely a bug in spigot that hasn't been patched yet.
I don't have time right now for bug testing... so I can only say stay on paper... which you should already be doing.

**Comment by SlimeDog** [comment]
Possible. The patches flow in the other direction, though. Waiting...

In the meantime, I've reverted to the previous Spigot build.

**Comment by SlimeDog** [comment]
[This](https://github.com/montlikadani/TabList/issues/307) may be of interest.

**Comment by SlimeDog** [comment]
[This](https://hub.spigotmc.org/jira/browse/SPIGOT-3247) strongly suggests that the issue is with how FishyLecterns handles comments. Only one other plugin, of 165+ that I test, fails on the Spigot update. Just a thought.

**Comment by SlimeDog** [comment]
> seems like a broken java refference error, if the plugin works on paper but doesn't on spigot, it's most likely a bug in spigot that hasn't been patched yet.
> I don't have time right now for bug testing... so I can only say stay on paper... which you should already be doing.

I test 165+ plugins on both Spigot **and** Paper. I am agnostic as to MC variant.

**Comment by Wolf2323** [comment]
I am confused,

I am the author of the newly added comment support in Bukkit/Spigot, so i has a look on this issue, to may help.

but if i look at the stacktrace i can not find the method `FishyLecterns.loadLecternsFromFile()` in the code

**Comment by FlailoftheLord** [comment]
https://github.com/FlailoftheLord/FishyLecterns/commit/52832ee76f153f8cc1625c34ad166ffb952eff0c

**Comment by SlimeDog** [comment]
Thanks. I confirm that FishyLecterns 1.3 is compatible with the Spigot change. Also with Spigot pre-change, and Paper.
